"""Tematy i podtematy promptu systemowego.

Klucz = temat w miejscowniku (po „Rozmowa o …”), wartość = podtematy w miejscowniku (po „o …”).
Do każdego zapytania losujemy podzbiór podtematów w losowej kolejności (zob. prompt.build_jobs),
żeby uniknąć mode collapse. Zmiana tej listy zmienia zadania wynikające z --master-seed, więc
wznawiany run musi używać tej samej wersji pliku.
"""

SUBTOPICS: dict[str, list[str]] = {
    "historii Polski": [
        "Słowianach i plemionach przed Mieszkiem", "Biskupinie", "Mieszku I i chrzcie Polski",
        "Bolesławie Chrobrym", "Mieszku II", "Kazimierzu Odnowicielu", "Bolesławie Krzywoustym",
        "rozbiciu dzielnicowym", "Henryku Pobożnym i bitwie pod Legnicą", "najazdach tatarskich",
        "lokacjach miast na prawie magdeburskim", "Kazimierzu Wielkim", "Jadwidze Andegaweńskiej",
        "Władysławie Jagielle", "unii polsko-litewskiej", "bitwie pod Grunwaldem", "zamkach krzyżackich",
        "Kazimierzu Jagiellończyku", "hołdzie pruskim", "Zygmuncie Starym i Zygmuncie Auguście",
        "unii lubelskiej", "Rzeczypospolitej Obojga Narodów", "wolnej elekcji",
        "Rzeczypospolitej szlacheckiej i liberum veto", "sarmatyzmie", "herbach i rodach szlacheckich",
        "Stefanie Batorym", "bitwie pod Kircholmem", "bitwie pod Kłuszynem",
        "Chmielnickim i powstaniu kozackim", "potopie szwedzkim", "pokoju w Oliwie", "Janie III Sobieskim",
        "odsieczy wiedeńskiej", "Augustach saskich", "konfederacji barskiej",
        "Stanisławie Auguście Poniatowskim", "Sejmie Czteroletnim", "Konstytucji 3 maja", "rozbiorach",
        "insurekcji kościuszkowskiej", "bitwie pod Racławicami", "rzezi Pragi", "Legionach Dąbrowskiego",
        "Napoleonie i Polakach", "Księstwie Warszawskim", "Kongresie Wiedeńskim", "Królestwie Polskim",
        "powstaniu listopadowym", "Wielkiej Emigracji", "Wiośnie Ludów", "rabacji galicyjskiej",
        "powstaniu styczniowym", "zaborze pruskim i Kulturkampfie", "autonomii galicyjskiej",
        "zaborze rosyjskim i rusyfikacji", "pracy organicznej", "rewolucji 1905 roku",
        "Legionach Piłsudskiego", "odzyskaniu niepodległości w 1918 roku", "traktacie wersalskim",
        "powstaniu wielkopolskim", "powstaniach śląskich", "plebiscytach na Śląsku i Mazurach",
        "Józefie Piłsudskim", "Romanie Dmowskim", "wojnie polsko-bolszewickiej", "cudzie nad Wisłą",
        "II Rzeczypospolitej", "przewrocie majowym", "budowie Gdyni i portu",
        "Centralnym Okręgu Przemysłowym", "Eugeniuszu Kwiatkowskim", "pakcie Ribbentrop-Mołotow",
        "kampanii wrześniowej", "Westerplatte", "obronie Warszawy w 1939 roku",
        "Enigmie i polskich kryptologach", "Katyniu", "Polskim Państwie Podziemnym",
        "armii Andersa", "bitwie o Monte Cassino", "Dywizjonie 303", "Witoldzie Pileckim",
        "Irenie Sendlerowej", "getcie warszawskim i powstaniu w getcie", "obozie Auschwitz",
        "Zagładzie Żydów na ziemiach polskich", "rzezi wołyńskiej", "powstaniu warszawskim",
        "okupacji niemieckiej i sowieckiej", "konferencji jałtańskiej", "zmianie granic po 1945 roku",
        "przesiedleniach powojennych", "żołnierzach wyklętych", "Bolesławie Bierucie i stalinizmie",
        "akcji „Wisła”", "PRL-u", "prymasie Wyszyńskim", "Czerwcu 1956", "Październiku 1956",
        "Gomułce i Gierku", "Marcu 1968", "wydarzeniach grudniowych 1970", "Radomiu 1976", "KOR-ze",
        "kartkach na żywność", "papieżu Janie Pawle II", "Sierpniu 1980 i Solidarności",
        "porozumieniach sierpniowych", "Lechu Wałęsie", "stanie wojennym", "Wojciechu Jaruzelskim",
        "Jerzym Popiełuszce", "Okrągłym Stole", "wyborach 4 czerwca 1989", "Tadeuszu Mazowieckim",
        "planie Balcerowicza", "transformacji ustrojowej", "wejściu Polski do NATO i Unii Europejskiej",
        "katastrofie smoleńskiej", "historii Żydów w Polsce", "Tatarach w Polsce",
        "historii swojego regionu", "Kresach Wschodnich",
    ],
    "polskiej kulturze i sztuce": [
        "Janie Kochanowskim", "Mikołaju Reju", "Ignacym Krasickim", "Adamie Mickiewiczu",
        "Juliuszu Słowackim", "Cyprianie Kamilu Norwidzie", "Aleksandrze Fredrze", "Henryku Sienkiewiczu",
        "Bolesławie Prusie", "Elizie Orzeszkowej", "Marii Konopnickiej", "Gabrieli Zapolskiej",
        "Stefanie Żeromskim", "Władysławie Reymoncie", "Stanisławie Wyspiańskim", "Bolesławie Leśmianie",
        "Julianie Tuwimie", "Marii Pawlikowskiej-Jasnorzewskiej", "Zofii Nałkowskiej", "Brunonie Schulzu",
        "Witoldzie Gombrowiczu", "Witkacym", "Jarosławie Iwaszkiewiczu", "Krzysztofie Kamilu Baczyńskim",
        "Czesławie Miłoszu", "Zbigniewie Herbercie", "Tadeuszu Różewiczu", "Wisławie Szymborskiej",
        "Halinie Poświatowskiej", "Annie Świrszczyńskiej", "Sławomirze Mrożku", "Tadeuszu Konwickim",
        "Marku Hłasce", "Edwardzie Stachurze", "Stanisławie Lemie", "Ryszardzie Kapuścińskim",
        "Hannie Krall", "Mariuszu Szczygle", "Wiesławie Myśliwskim", "Adamie Zagajewskim", "Ewie Lipskiej",
        "Oldze Tokarczuk", "Dorocie Masłowskiej", "Szczepanie Twardochu", "Jacku Dukaju",
        "Andrzeju Sapkowskim", "romantyzmie", "pozytywizmie", "Młodej Polsce", "dwudziestoleciu międzywojennym",
        "poezji współczesnej", "reportażu", "fantastyce", "kryminałach", "literaturze dziecięcej",
        "Nagrodzie Nike", "teatrze i kabarecie", "Tadeuszu Kantorze", "Jerzym Grotowskim",
        "Krystianie Lupie", "Teatrze Narodowym", "Piwnicy pod Baranami", "Kabarecie Starszych Panów",
        "Agnieszce Osieckiej", "Jeremim Przyborze", "malarstwie Matejki i Malczewskiego",
        "Józefie Chełmońskim", "Wojciechu Kossaku", "Oldze Boznańskiej", "Zdzisławie Beksińskim",
        "Tamarze Łempickiej", "Nikiforze", "Magdalenie Abakanowicz", "polskim plakacie",
        "polskim designie", "architekturze zabytkowej", "modernizmie w Gdyni", "sztuce ludowej i wycinankach",
        "pisankach", "koronce koniakowskiej", "ceramice z Bolesławca", "szopkach krakowskich",
        "polskich legendach i baśniach", "obrzędach i zwyczajach świątecznych",
        "„Tytusie, Romku i A’Tomku”", "„Kajku i Kokoszu”", "polskich komiksach", "polskich grach wideo",
        "Muzeum Narodowym", "Muzeum POLIN", "Muzeum Powstania Warszawskiego", "muzeach i festiwalach",
        "polskich podcastach i youtuberach", "Wielkiej Orkiestrze Świątecznej Pomocy",
    ],
    "lekturach szkolnych": [
        "„Bogurodzicy”", "„Kazaniach świętokrzyskich”", "„Trenach” Jana Kochanowskiego",
        "„Odprawie posłów greckich”", "fraszkach Kochanowskiego", "„Antygonie”", "„Królu Edypie”",
        "„Odysei”", "„Iliadzie”", "mitologii greckiej", "Biblii jako lekturze", "„Pieśni o Rolandzie”",
        "„Makbecie”", "„Hamlecie”", "„Romeo i Julii”", "„Skąpcu” Moliera", "bajkach Krasickiego",
        "„Balladach i romansach”", "„Romantyczności” Mickiewicza", "„Świtezi”", "„Sonetach krymskich”",
        "„Konradzie Wallenrodzie”", "„Dziadach” cz. II", "„Dziadach” cz. III", "„Panu Tadeuszu”",
        "„Kordianie”", "„Balladynie”", "„Nie-Boskiej komedii”", "„Zemście” Fredry",
        "„Ślubach panieńskich”", "„Lalce” Bolesława Prusa", "„Katarynce”", "„Kamizelce”",
        "„Latarniku”", "„Janku Muzykancie”", "„Nad Niemnem”", "„Potopie”", "„Krzyżakach”",
        "„Quo vadis”", "„W pustyni i w puszczy”", "„Zbrodni i karze”", "„Weselu” Wyspiańskiego",
        "„Chłopach” Reymonta", "„Ludziach bezdomnych”", "„Syzyfowych pracach”", "„Przedwiośniu”",
        "„Granicy” Nałkowskiej", "„Ferdydurke”", "„Sklepach cynamonowych”", "„Medalionach”",
        "opowiadaniach Tadeusza Borowskiego", "„Innym świecie” Herlinga-Grudzińskiego",
        "„Kamieniach na szaniec”", "„Zdążyć przed Panem Bogiem”", "„Tangu” Mrożka", "„Dżumie” Camusa",
        "„Procesie” Kafki", "„Mistrzu i Małgorzacie”", "„Roku 1984”", "„Folwarku zwierzęcym”",
        "„Małym Księciu”", "„Opowieściach z Narnii”", "„Hobbicie”", "„Akademii pana Kleksa”",
        "„Dzieciach z Bullerbyn”", "„Ani z Zielonego Wzgórza”", "„Chłopcach z Placu Broni”",
        "„Tajemniczym ogrodzie”", "„Sposobie na Alcybiadesa”", "„Szatanie z siódmej klasy”",
        "„Mikołajku”", "„Kubusiu Puchatku”", "„Pinokiu”", "„Opowieści wigilijnej”",
        "„Panu Wołodyjowskim”", "„Ogniem i mieczem”", "„Solarisie”", "„Cyberiadzie”",
        "„Wiedźminie” jako lekturze", "„Rozmowach z katem”", "„Pamiętniku z powstania warszawskiego”",
        "„Kwiatach polskich”", "„Ziemi obiecanej”", "„Moralności pani Dulskiej”",
        "streszczeniach lektur", "opracowaniach lektur", "motywach literackich na maturze",
        "lekturach obowiązkowych i uzupełniających", "czytaniu lektur ze zrozumieniem",
    ],
    "polskim kinie i serialach": [
        "„Misiu” Barei", "„Rejsie”", "„Seksmisji”", "„Vabanku”", "„Kilerze”", "„Psach” Pasikowskiego",
        "„Dniu świra”", "„Chłopakach nie płaczą”", "„Samych swoich”", "„Nie ma mocnych”",
        "„Kochajmy się”", "„Krzyżakach” Aleksandra Forda", "„Potopie” Hoffmana",
        "„Panu Wołodyjowskim” Hoffmana", "„Popiele i diamencie”", "„Człowieku z marmuru”",
        "„Człowieku z żelaza”", "„Ziemi obiecanej” Wajdy", "„Weselu” Wajdy", "„Katyniu” Wajdy",
        "„Dekalogu” Kieślowskiego", "trylogii „Trzy kolory”", "„Podwójnym życiu Weroniki”",
        "„Nożu w wodzie”", "„Pianiście” Polańskiego", "„Idzie”", "„Zimnej wojnie”", "„Bożym Ciele”",
        "„Wołyniu”", "„Pokłosiu”", "„Drogówce”", "„Klerze”", "„Służbach specjalnych”",
        "„Bogach” o Zbigniewie Relidze", "„Sali samobójców”", "„Body/Ciało”", "„Wszystkich nieobecnych”",
        "animowanych „Chłopach”", "„Twoim Vincencie”", "„Kac Wawa”", "„Listach do M.”",
        "„Planecie singli”", "„Testosteronie”", "„Jak rozpętałem drugą wojnę światową”",
        "„Czterech pancernych i psie”", "„Stawce większej niż życie”", "„Czterdziestolatku”",
        "„Alternatywach 4”", "„Zmiennikach”", "„Domu” Łomnickiego", "„Klanie”", "„M jak miłość”",
        "„Na dobre i na złe”", "„Ranczu”", "„Świecie według Kiepskich”", "„Ojcu Mateuszu”",
        "„Czasie honoru”", "„Wielkiej wodzie”", "„1983”", "„Rojst”", "„Belfrze”", "„Watasze”",
        "„Ślepnąc od świateł”", "„Królu” Twardocha", "„Kruku”", "„Wiedźminie” Netfliksa",
        "„Bolku i Lolku”", "„Reksiu”", "„Krecie”", "„Misiu Uszatku”",
        "Andrzeju Wajdzie", "Krzysztofie Kieślowskim", "Romanie Polańskim", "Agnieszce Holland",
        "Pawle Pawlikowskim", "Wojciechu Smarzowskim", "Stanisławie Barei", "Juliuszu Machulskim",
        "Krzysztofie Zanussim", "Andrzeju Żuławskim", "Zbigniewie Cybulskim", "Danielu Olbrychskim",
        "Krystynie Jandzie", "Bogusławie Lindzie", "Januszu Gajosie", "Joannie Kulig",
        "Macieju Stuhrze i Jerzym Stuhrze", "Arturze Żmijewskim", "Festiwalu w Gdyni",
        "Oscarach dla polskich filmów", "dubbingu i lektorze", "polskich filmach na Netfliksie",
    ],
    "polskiej muzyce": [
        "Fryderyku Chopinie", "Konkursie Chopinowskim", "Stanisławie Moniuszce", "Karolu Szymanowskim",
        "Witoldzie Lutosławskim", "Krzysztofie Pendereckim", "Henryku Góreckim", "Wojciechu Kilarze",
        "Zbigniewie Preisnerze", "Janie A.P. Kaczmarku", "muzyce filmowej", "operze i filharmonii",
        "polskim jazzie", "Krzysztofie Komedzie", "Tomaszu Stańce", "Jazz Jamboree",
        "Czesławie Niemenie", "Annie German", "Marku Grechucie", "Krzysztofie Krawczyku",
        "Zbigniewie Wodeckim", "Maryli Rodowicz", "Edycie Geppert", "Edycie Górniak", "Kayah",
        "Kasi Nosowskiej i Heyu", "Republice i Grzegorzu Ciechowskim", "Maanamie i Korze", "Perfekcie",
        "Lady Pank", "Budce Suflera", "Dżemie", "Kulcie", "T.Love", "Wilkach", "Myslovitz", "Comie",
        "Behemocie", "Vaderze", "polskim rocku", "polskim metalu", "polskim punku",
        "Paktofonice", "Kalibrze 44", "O.S.T.R.", "Pezecie", "Sokole", "Taco Hemingwayu",
        "Quebonafide", "Macie", "polskim hip-hopie", "Dawidzie Podsiadle", "Sanah", "Kortezie",
        "Darii Zawiałow", "Brodce", "Margaret", "disco polo", "Zenku Martyniuku", "Eurowizji",
        "festiwalu w Opolu", "Sopot Festival", "Open'erze", "Pol'and'Rock Festival", "OFF Festivalu",
        "Męskim Graniu", "muzyce ludowej", "zespole „Mazowsze”", "kolędach i pastorałkach",
        "pieśniach patriotycznych", "hymnie narodowym", "piosenkach dla dzieci", "chórach",
        "orkiestrach dętych", "nauce gry na gitarze", "nauce gry na pianinie", "lekcjach śpiewu",
        "szkole muzycznej", "winylach", "koncertach", "karaoke", "tekstach piosenek",
    ],
    "polskiej kuchni": [
        "pierogach", "pierogach ruskich", "uszkach do barszczu", "bigosie", "żurku i zakwasie",
        "barszczu czerwonym", "rosole", "zupie pomidorowej", "zupie ogórkowej", "kapuśniaku",
        "krupniku", "grochówce", "zupie szczawiowej", "kwaśnicy", "flakach", "chłodniku",
        "zupie grzybowej", "kotlecie schabowym", "kotletach mielonych", "zrazach", "schabie pieczonym",
        "kaczce z jabłkami", "roladzie śląskiej", "modrej kapuście", "gołąbkach", "golonce", "kaszance",
        "fasolce po bretońsku", "gulaszu", "plackach ziemniaczanych", "plackach po węgiersku",
        "kopytkach", "kluskach śląskich", "pyzach", "leniwych", "naleśnikach", "racuchach",
        "pyrach z gzikiem", "zapiekankach", "obwarzankach krakowskich", "rogalach świętomarcińskich",
        "kiszonkach", "kiszeniu ogórków", "kiszonej kapuście", "grzybach i grzybobraniu",
        "wędlinach i kiełbasach", "domowych wędlinach", "wędzeniu", "smalcu", "tatarze",
        "nóżkach w galarecie", "śledziach", "karpiu", "sałatce jarzynowej", "mizerii", "surówkach",
        "ćwikle i chrzanie", "oscypku i serach regionalnych", "twarogu", "chlebie na zakwasie",
        "pieczeniu chleba w domu", "chlebie żytnim", "dwunastu potrawach wigilijnych", "kutii",
        "wielkanocnym stole", "babce wielkanocnej", "mazurkach", "pączkach i tłustym czwartku",
        "faworkach", "szarlotce", "sernikach i makowcach", "kremówkach", "pierniku toruńskim",
        "drożdżówkach", "kompocie", "konfiturach i dżemach", "przetworach", "miodzie", "nalewkach",
        "piwie kraftowym", "kawie i kawiarniach", "herbacie", "kaszach", "potrawach z ziemniaków",
        "przyprawach", "kuchni śląskiej", "kuchni podhalańskiej", "kuchni kaszubskiej",
        "kuchni kresowej", "kuchni żydowskiej w Polsce", "wegetariańskich wersjach polskich dań",
        "kuchni wegańskiej", "kuchni bezglutenowej", "kuchni dla diabetyków", "niedzielnym obiedzie",
        "obiadach dla dzieci", "przepisach babci", "gotowaniu przy małym budżecie", "planowaniu posiłków",
        "meal prepie", "marnowaniu jedzenia", "przechowywaniu i mrożeniu żywności", "grillowaniu",
        "barach mlecznych", "Magdzie Gessler", "„Kuchennych rewolucjach”", "Robercie Makłowiczu",
        "Karolu Okrasie", "Wojciechu Modeście Amaro", "Ewie Wachowicz", "Pascalu Brodnickim",
        "Michelu Moranie", "Annie Starmach", "„MasterChefie”", "Thermomiksie", "robocie kuchennym",
        "frytkownicy beztłuszczowej", "szybkowarze", "wolnowarze", "kuchence indukcyjnej",
        "żeliwnych garnkach", "patelniach", "nożach kuchennych",
    ],
    "sprawach urzędowych w Polsce": [
        "dowodzie osobistym", "dowodzie osobistym dla dziecka", "paszporcie", "paszporcie dla dziecka",
        "paszporcie tymczasowym", "meldunku", "meldunku czasowym", "zmianie adresu", "numerze PESEL",
        "zastrzeżeniu numeru PESEL", "zmianie nazwiska", "ślubie cywilnym", "rejestracji urodzenia dziecka",
        "aktach stanu cywilnego", "akcie zgonu i pogrzebie", "zasiłku pogrzebowym", "obywatelstwie polskim",
        "Karcie Polaka", "zeznaniu PIT", "PIT-37 i PIT-36", "Twoim e-PIT", "rozliczeniu wspólnym z małżonkiem",
        "uldze dla młodych", "zwrocie podatku", "uldze na dzieci", "uldze termomodernizacyjnej",
        "podatku od spadków i darowizn", "zgłoszeniu darowizny od rodziny", "urzędzie skarbowym",
        "e-Urzędzie Skarbowym", "kontroli skarbowej", "jednoosobowej działalności gospodarczej", "CEIDG",
        "VAT", "kasie fiskalnej", "KRS i spółkach", "składkach ZUS", "uldze na start i małym ZUS-ie",
        "emeryturze", "emeryturze stażowej", "trzynastej i czternastej emeryturze", "rencie rodzinnej",
        "rencie z tytułu niezdolności do pracy", "zwolnieniu lekarskim", "e-zwolnieniu", "zasiłku opiekuńczym",
        "urlopie macierzyńskim i rodzicielskim", "świadczeniu 800 plus", "becikowym",
        "karcie dużej rodziny", "funduszu alimentacyjnym", "dodatku mieszkaniowym", "dodatku osłonowym",
        "orzeczeniu o niepełnosprawności", "karcie parkingowej", "świadczeniu pielęgnacyjnym",
        "programie Czyste Powietrze", "dotacjach na fotowoltaikę", "NFZ i skierowaniach", "e-recepcie",
        "Internetowym Koncie Pacjenta", "rejestracji samochodu", "rejestracji auta z zagranicy",
        "dowodzie rejestracyjnym", "przeglądzie technicznym", "karach z UFG za brak OC", "prawie jazdy",
        "utracie prawa jazdy", "mandatach", "punktach karnych", "abonamencie RTV", "opłacie śmieciowej",
        "rejestracji i chipowaniu psa", "pozwoleniu na broń", "pozwoleniu na wycinkę drzewa",
        "zgłoszeniu budowy altany", "warunkach zabudowy", "pozwoleniu na budowę", "mapach geodezyjnych",
        "podziale działki", "przekształceniu użytkowania wieczystego", "księgach wieczystych",
        "sprzedaży mieszkania", "podatku od nieruchomości", "umowie najmu okazjonalnego", "eksmisji",
        "rozwodzie", "alimentach", "ustaleniu ojcostwa", "władzy rodzicielskiej",
        "zgodzie na wyjazd dziecka za granicę", "spadku i notariuszu", "pełnomocnictwie",
        "tłumaczu przysięgłym", "apostille i legalizacji dokumentów", "profilu zaufanym i mObywatelu",
        "ePUAP", "e-Doręczeniach", "podpisie kwalifikowanym", "wyborach", "budżecie obywatelskim",
        "radzie osiedla", "petycji do gminy", "skardze do Rzecznika Praw Obywatelskich",
        "urzędzie pracy i zasiłku", "zaświadczeniu o niekaralności", "zgłoszeniu kradzieży",
        "reklamacji i prawach konsumenta", "sprawach w sądzie", "e-sądzie i nakazie zapłaty", "mediacji",
        "komorniku", "przedawnieniu długów", "upadłości konsumenckiej", "odwołaniu od decyzji",
        "dostępie do informacji publicznej",
    ],
    "języku polskim": [
        "pisowni ó i u", "pisowni rz i ż", "pisowni ch i h", "pisowni „nie” z różnymi częściami mowy",
        "pisowni łącznej i rozdzielnej", "pisowni „-by” z czasownikami", "pisowni „pół”", "pisowni dat",
        "pisowni liczebników", "pisowni nazw geograficznych", "przecinkach", "średniku", "myślniku i dywizie",
        "cudzysłowie", "wielkiej i małej literze", "skrótach „np.” i „itp.”", "skrótowcach",
        "odmianie nazwisk", "odmianie imion obcych", "odmianie nazw miast", "odmianie liczebników",
        "liczebnikach zbiorowych", "liczbie mnogiej rzeczowników", "rodzajach gramatycznych", "przypadkach",
        "dopełniaczu", "bierniku", "narzędniku", "wołaczu", "stopniowaniu przymiotników",
        "aspekcie czasowników", "trybie przypuszczającym", "czasownikach zwrotnych", "imiesłowach",
        "imiesłowach przysłówkowych", "stronie biernej", "szyku zdania", "zdaniach złożonych",
        "mowie zależnej", "zaimku „swój”", "formach „poszłem” i „poszedłem”", "„wziąć” i „wziąść”",
        "„włączać” i „włanczać”", "„tę” i „tą”", "„ubrać” i „założyć”", "„bynajmniej” i „przynajmniej”",
        "„w każdym razie” i „w każdym bądź razie”", "„na pewno” i „w ogóle”", "akcentowaniu wyrazów",
        "wymowie „ę” i „ą”", "formach grzecznościowych", "zwrotach „Pan” i „Pani”",
        "zwrotach grzecznościowych w listach", "związkach frazeologicznych", "przysłowiach",
        "pochodzeniu słów", "słowotwórstwie", "zdrobnieniach", "neologizmach", "archaizmach",
        "staropolszczyźnie", "zapożyczeniach z angielskiego", "anglicyzmach w pracy", "korporacyjnym slangu",
        "slangu młodzieżowym", "języku internetu i memach", "skrótach w SMS-ach", "emoji", "wulgaryzmach",
        "eufemizmach", "języku prawniczym", "języku urzędowym", "gwarach i regionalizmach",
        "gwarze poznańskiej", "gwarze warszawskiej", "akcencie śląskim", "dialektach góralskich",
        "języku śląskim i kaszubskim", "polskich znakach diakrytycznych", "wymowie", "logopedii",
        "dwujęzyczności dzieci", "częstych błędach językowych", "feminatywach", "transkrypcji obcych nazwisk",
        "nazwiskach i ich pochodzeniu", "imionach i ich znaczeniu", "nazwach miejscowości i ich odmianie",
        "Radzie Języka Polskiego", "słownikach języka polskiego", "pisaniu oficjalnych maili",
        "pisaniu CV i listu motywacyjnego", "pisaniu podań", "pisaniu wypracowań", "pisaniu przemówień",
        "pisaniu życzeń", "pisaniu kondolencji", "korekcie tekstu", "synonimach",
        "różnicach znaczeniowych podobnych słów", "zapisie dialogów", "rymach i wierszach",
        "nauce czytania u dzieci", "nauce polskiego jako obcego",
    ],
    "polskiej geografii i przyrodzie": [
        "Tatrach", "Rysach", "Giewoncie", "Morskim Oku", "Dolinie Kościeliskiej", "Kasprowym Wierchu",
        "Pieninach", "Gorcach", "Babiej Górze", "Beskidach", "Bieszczadach", "Sudetach", "Karkonoszach",
        "Śnieżce", "Górach Stołowych", "Górach Świętokrzyskich", "Kotlinie Kłodzkiej", "Roztoczu",
        "Jurze Krakowsko-Częstochowskiej", "Szlaku Orlich Gniazd", "Mazurach", "Śniardwach", "Mamrach",
        "jeziorze Hańcza", "Jeziorze Solińskim", "Kanale Augustowskim", "Kanale Elbląskim", "Kaszubach",
        "Pomorzu", "Warmii", "Podlasiu", "Mazowszu", "Kujawach", "Wielkopolsce", "Śląsku", "Dolnym Śląsku",
        "Opolszczyźnie", "Lubelszczyźnie", "Podkarpaciu", "Ziemi Lubuskiej", "Suwalszczyźnie", "Żuławach",
        "Bałtyku i plażach", "Helu i Mierzei Wiślanej", "Zatoce Gdańskiej", "Zalewie Wiślanym",
        "Zalewie Szczecińskim", "Słowińskim Parku Narodowym", "wydmach", "Wiśle", "Odrze", "Warcie",
        "Sanie", "Dunajcu", "Pilicy", "Bugu i Narwi", "jeziorach", "torfowiskach", "Puszczy Białowieskiej",
        "Biebrzańskim Parku Narodowym", "Kampinoskim Parku Narodowym", "Ojcowskim Parku Narodowym",
        "Bieszczadzkim Parku Narodowym", "Wigierskim Parku Narodowym", "parkach narodowych",
        "rezerwatach przyrody", "ochronie przyrody", "roślinach chronionych", "jaskiniach",
        "Pustyni Błędowskiej", "żubrach", "łosiach", "jeleniach i sarnach", "kozicach i świstakach",
        "bobrach", "fokach bałtyckich", "wilkach i rysiach", "niedźwiedziach", "dzikach w miastach",
        "bocianach", "żurawiach", "orłach", "ptakach i ich przylotach", "żmijach", "żabach i traszkach",
        "motylach", "pszczołach", "kleszczach", "kornikach", "dębach i bukach", "grzybach leśnych",
        "jagodach i borówkach", "zbieraniu ziół", "gatunkach inwazyjnych", "lasach i wycince drzew",
        "klimacie i pogodzie", "porach roku", "upałach", "zimach bez śniegu", "burzach i nawałnicach",
        "trąbach powietrznych", "suszy i powodziach", "retencji wody", "zmianach klimatu w Polsce", "smogu",
        "zanieczyszczeniu Bałtyku", "katastrofie ekologicznej na Odrze", "segregacji śmieci",
        "kopalniach i węglu", "kopalniach soli", "bursztynie", "energii odnawialnej",
        "elektrowni jądrowej w Polsce", "rolnictwie", "województwach", "dużych miastach",
        "małych miasteczkach i wsiach", "ogrodach i działkach",
    ],
    "codziennym życiu w Polsce": [
        "wynajmie mieszkania", "przeprowadzce", "kredycie hipotecznym", "czynszu w spółdzielni",
        "rachunkach za prąd i gaz", "rachunkach za wodę", "abonamencie telefonicznym", "internecie domowym",
        "zakupach w dyskontach", "Biedronce i Lidlu", "Żabce", "promocjach i gazetkach",
        "kartach lojalnościowych", "zakupach na targu", "zakupach w internecie", "zakupach na Vinted i OLX",
        "zwrotach towarów", "paczkomatach", "kurierach", "poczcie", "dostawach jedzenia", "cenach i inflacji",
        "komunikacji miejskiej", "biletach komunikacji miejskiej", "Uberze i Bolcie", "taksówkach",
        "rowerach miejskich", "hulajnogach elektrycznych", "parkowaniu w mieście", "korkach",
        "stacjach benzynowych", "cenach paliwa", "myjniach samochodowych", "podróżach pociągiem",
        "dojazdach samochodem", "dojazdach do pracy", "pracy biurowej", "pracy zdalnej", "pracy na zmiany",
        "umowie o pracę i umowie zleceniu", "szukaniu pracy", "lekarzu rodzinnym",
        "kolejkach do specjalistów", "dentyście", "aptece", "fryzjerze", "szewcu i krawcu", "pralni",
        "przedszkolu i szkole", "maturze", "studiach", "opiece nad dziećmi", "opiece nad starszymi rodzicami",
        "zwierzętach domowych", "remontach", "sprzątaniu", "życiu w bloku", "życiu w kamienicy",
        "domu pod miastem", "życiu na wsi", "windzie w bloku", "sąsiadach i wspólnocie mieszkaniowej",
        "hałasie", "sąsiedzkiej pomocy", "parafii i kościele", "niedzielach handlowych",
        "świętach państwowych", "długich weekendach", "weekendach i wolnym czasie", "spacerach z psem",
        "parkach miejskich", "basenach i saunach", "siłowniach plenerowych", "kinie i teatrze",
        "kawiarniach", "barach i pubach", "festynach i odpustach", "dożynkach",
        "urlopie nad morzem i w górach", "majówce", "feriach zimowych", "świętach rodzinnych", "Wigilii",
        "Wielkanocy", "śmigusie-dyngusie", "Bożym Ciele", "Wszystkich Świętych", "imieninach", "urodzinach",
        "osiemnastkach", "parapetówkach", "prezentach", "Dniu Matki i Dniu Ojca", "Dniu Babci i Dziadka",
        "walentynkach", "Dniu Kobiet", "mikołajkach", "andrzejkach", "sylwestrze", "ślubach i weselach",
        "chrzcinach", "pogrzebach i stypach", "bankowości i BLIK-u", "oszczędzaniu",
    ],
    "sporcie w Polsce": [
        "reprezentacji Polski w piłce nożnej", "mundialu 1974", "mundialu 1982", "Euro 2012", "Lidze Narodów",
        "mundialu", "mistrzostwach Europy", "Lidze Mistrzów", "Ekstraklasie", "Lechu Poznań",
        "Legii Warszawa", "Wiśle Kraków", "Cracovii", "Górniku Zabrze", "Rakowie Częstochowa",
        "Jagiellonii Białystok", "Pogoni Szczecin", "Śląsku Wrocław", "Widzewie Łódź", "derbach",
        "Kazimierzu Górskim", "Kazimierzu Deynie", "Zbigniewie Bońku", "Grzegorzu Lacie", "Jerzym Dudku",
        "Robercie Lewandowskim", "Jakubie Błaszczykowskim", "Wojciechu Szczęsnym", "Piotrze Zielińskim",
        "piłce nożnej kobiet", "Ewie Pajor", "siatkówce", "PlusLidze", "ZAKSIE Kędzierzyn-Koźle",
        "Jastrzębskim Węglu", "Bartoszu Kurku", "Wilfredo Leonie", "Nikoli Grbiciu", "reprezentacji siatkarek",
        "tenisie i Idze Świątek", "Agnieszce Radwańskiej", "Hubercie Hurkaczu", "Magdzie Linette",
        "tenisie stołowym", "badmintonie", "padlu i squashu", "skokach narciarskich", "Turnieju Czterech Skoczni",
        "Wielkiej Krokwi", "Adamie Małyszu", "Kamilu Stochu", "Dawidzie Kubackim", "Piotrze Żyle",
        "Justynie Kowalczyk", "narciarstwie biegowym", "narciarstwie zjazdowym", "skialpinizmie", "snowboardzie",
        "łyżwiarstwie", "Zbigniewie Bródce", "Natalii Czerwonce", "hokeju", "żużlu", "Bartoszu Zmarzliku",
        "Tomaszu Gollobie", "Unii Leszno", "Motorze Lublin", "piłce ręcznej", "Orlen Wiśle Płock",
        "Industrii Kielce", "koszykówce", "Marcinie Gortacie", "Jeremym Sochanie", "lekkoatletyce",
        "Irenie Szewińskiej", "Robercie Korzeniowskim", "Anicie Włodarczyk", "Wojciechu Nowickim",
        "Pawle Fajdku", "Adamie Kszczocie", "Natalii Kaczmarek", "Ewie Swobodzie", "pływaniu",
        "Otylii Jędrzejczak", "igrzyskach olimpijskich", "sporcie niepełnosprawnych", "kolarstwie",
        "Tour de Pologne", "Michale Kwiatkowskim", "Rafale Majce", "kolarstwie górskim", "maratonach",
        "Maratonie Warszawskim", "ultramaratonach", "parkrunach", "triathlonie", "bieganiu dla początkujących",
        "nordic walking", "jeździe na rowerze", "siłowni i fitnessie", "crossficie", "jodze",
        "podnoszeniu ciężarów", "Mariuszu Pudzianowskim", "żeglarstwie", "windsurfingu i kitesurfingu",
        "kajakach", "wioślarstwie", "nurkowaniu", "wspinaczce", "polskich himalaistach", "Jerzym Kukuczce",
        "Wandzie Rutkiewicz", "Andrzeju Bargielu", "szachach", "Janie-Krzysztofie Dudzie",
        "sportach walki i boksie", "Andrzeju Gołocie", "Tomaszu Adamku", "MMA i galach KSW",
        "Joannie Jędrzejczyk", "Janie Błachowiczu", "jeździectwie", "golfie", "darcie i bilardzie",
        "rajdach samochodowych", "Robercie Kubicy", "e-sporcie", "kibicowaniu i stadionach",
        "wychowaniu fizycznym w szkole", "kontuzjach sportowych", "diecie sportowca",
    ],
    "zdrowiu": [
        "przeziębieniu i grypie", "COVID-19", "anginie", "zapaleniu ucha", "ospie wietrznej", "odrze",
        "szczepieniach", "szczepieniu przeciw HPV", "alergiach", "astmie", "migrenie", "zawrotach głowy",
        "szumach usznych", "bólu pleców", "rwie kulszowej", "dyskopatii", "zwyrodnieniu stawów", "osteoporozie",
        "cukrzycy", "insulinooporności", "Hashimoto i niedoczynności tarczycy", "anemii", "cholesterolu",
        "nadciśnieniu", "chorobach serca", "zawale serca", "udarze", "żylakach", "refluksie",
        "zespole jelita drażliwego", "celiakii", "nietolerancji laktozy", "kamicy nerkowej",
        "zapaleniu pęcherza", "hemoroidach", "raku piersi i mammografii", "cytologii", "raku prostaty",
        "kolonoskopii", "znamionach i nowotworach skóry", "łuszczycy", "atopowym zapaleniu skóry",
        "skórze i trądziku", "trądziku różowatym", "łysieniu", "opalaniu i kremach z filtrem",
        "zdrowej diecie", "odchudzaniu", "liczeniu kalorii", "poście przerywanym", "diecie keto",
        "witaminach i suplementach", "witaminie D", "magnezie", "probiotykach", "śnie i bezsenności",
        "chrapaniu i bezdechu sennym", "stresie", "wypaleniu", "depresji", "zaburzeniach lękowych",
        "atakach paniki", "ADHD u dorosłych", "autyzmie", "uzależnieniu od telefonu", "uzależnieniu od hazardu",
        "wizycie u psychologa", "psychiatrze", "terapii", "lekach przeciwdepresyjnych",
        "zdrowiu psychicznym nastolatków", "badaniach okresowych", "morfologii krwi",
        "badaniach profilaktycznych", "pierwszej pomocy", "resuscytacji i defibrylatorze AED",
        "oparzeniach", "udarze cieplnym", "odmrożeniach", "ukąszeniach owadów", "kleszczach i boreliozie",
        "kleszczowym zapaleniu mózgu", "antybiotykach", "lekach bez recepty", "ibuprofenie i paracetamolu",
        "zdrowiu dzieci", "ciąży", "menopauzie", "zdrowiu seniorów", "zębach", "leczeniu kanałowym",
        "implantach zębowych", "aparacie ortodontycznym", "wzroku i okularach", "zaćmie i jaskrze",
        "laserowej korekcji wzroku", "słuchu", "rzucaniu palenia", "alkoholu", "aktywności fizycznej",
        "chodzeniu 10 tysięcy kroków", "rehabilitacji", "fizjoterapii", "sanatorium",
        "prywatnych abonamentach medycznych", "teleporadzie", "szpitalnym oddziale ratunkowym",
        "opiece paliatywnej i hospicjum", "ergonomii pracy przy komputerze",
    ],
    "pracy i karierze": [
        "pisaniu CV", "liście motywacyjnym", "portfolio", "referencjach", "rekrutacji online",
        "testach rekrutacyjnych", "rozmowie kwalifikacyjnej", "pierwszej pracy", "stażu",
        "pracy dla studentów", "pracy sezonowej", "okresie próbnym", "umowie na czas określony",
        "negocjacjach wynagrodzenia", "widełkach płacowych", "jawności wynagrodzeń", "podwyżce", "awansie",
        "ocenach rocznych", "feedbacku", "zmianie branży", "zmianie zawodu po czterdziestce",
        "przekwalifikowaniu", "kursach i certyfikatach", "studiach podyplomowych", "MBA",
        "certyfikatach językowych", "prawie jazdy kategorii C", "pracy zdalnej", "pracy hybrydowej",
        "coworkingu", "pracy zmianowej", "umowie B2B", "umowie o dzieło", "okresie wypowiedzenia",
        "wypowiedzeniu umowy", "zwolnieniu z pracy", "zwolnieniu dyscyplinarnym", "odprawie",
        "świadectwie pracy", "urlopie wypoczynkowym", "nadgodzinach", "płacy minimalnej", "PPK",
        "benefitach pracowniczych", "BHP", "mobbingu", "dyskryminacji w pracy", "równości płac",
        "Państwowej Inspekcji Pracy", "sądzie pracy", "związkach zawodowych", "strajkach",
        "relacjach z szefem", "konfliktach w pracy", "pracy w zespole", "zarządzaniu zespołem",
        "pierwszej roli menedżera", "delegowaniu zadań", "zarządzaniu czasem", "prokrastynacji",
        "spotkaniach online", "Teamsach i Slacku", "mailach służbowych", "prezentacjach",
        "wystąpieniach publicznych", "korporacyjnym żargonie", "pracy w korporacji", "pracy w budżetówce",
        "pracy w handlu", "pracy na kasie", "pracy w magazynie", "pracy kuriera", "pracy kierowcy",
        "pracy w gastronomii", "pracy w hotelarstwie", "pracy w budowlance", "pracy elektryka",
        "pracy hydraulika", "pracy w IT", "pracy programisty", "pracy testera oprogramowania",
        "pracy w data science", "pracy w UX", "pracy w marketingu", "pracy w HR", "pracy w księgowości",
        "pracy w bankowości", "pracy w call center", "pracy nauczyciela", "pracy w służbie zdrowia",
        "pracy pielęgniarki", "pracy ratownika medycznego", "pracy w aptece", "pracy w policji",
        "pracy w wojsku", "pracy strażaka", "pracy w rolnictwie", "pracy w Niemczech",
        "pracy zdalnej z zagranicy", "powrocie z emigracji", "własnej firmie", "freelancingu", "LinkedInie",
        "wypaleniu zawodowym", "równowadze między pracą a życiem", "przejściu na emeryturę",
        "pracy na emeryturze",
    ],
    "finansach osobistych": [
        "budżecie domowym", "metodzie kopertowej", "zasadzie 50/30/20", "minimalizmie finansowym",
        "funduszu awaryjnym", "koncie osobistym", "darmowym koncie bankowym", "przelewach natychmiastowych",
        "BLIK-u", "karcie wielowalutowej", "Revolucie", "kantorach internetowych", "wymianie walut",
        "kursie złotego", "inflacji", "lokatach", "kontach oszczędnościowych", "obligacjach skarbowych",
        "obligacjach indeksowanych inflacją", "obligacjach rodzinnych", "oszczędzaniu na emeryturę",
        "IKE i IKZE", "emeryturze z ZUS i OFE", "funduszach inwestycyjnych", "inwestowaniu w ETF-y",
        "akcjach na GPW", "dywidendach", "rachunkach maklerskich", "giełdzie", "złocie i srebrze",
        "kryptowalutach", "bitcoinie", "PIT-38 i podatku od kryptowalut", "podatku Belki",
        "wcześniejszej emeryturze i FIRE", "kredycie gotówkowym", "chwilówkach", "karcie kredytowej",
        "debecie", "zakupach na raty", "leasingu", "pożyczkach od rodziny", "konsolidacji długów", "BIK-u",
        "Krajowym Rejestrze Długów", "zadłużeniu", "windykacji", "komornikach", "kupnie pierwszego mieszkania",
        "wkładzie własnym", "zdolności kredytowej", "programach rządowych na mieszkanie", "spłacie kredytu",
        "nadpłacie kredytu", "refinansowaniu kredytu", "WIBOR-ze i WIRON-ie", "frankowiczach",
        "wynajmie jako inwestycji", "podatku od wynajmu i ryczałcie", "flippingu mieszkań",
        "ubezpieczeniu na życie", "OC i AC", "ubezpieczeniu mieszkania", "ubezpieczeniu turystycznym",
        "ubezpieczeniu NNW dziecka", "prywatnym ubezpieczeniu zdrowotnym", "kieszonkowym dla dzieci",
        "rachunku dla dziecka", "oszczędzaniu na studia dziecka", "kosztach utrzymania dziecka",
        "finansach w związku", "kosztach ślubu", "kosztach pogrzebu", "rachunkach i opłatach",
        "oszczędzaniu na zakupach spożywczych", "oszczędzaniu na wakacje", "zakupach z drugiej ręki",
        "dorabianiu po godzinach", "oszustwach na BLIK-a", "phishingu bankowym", "oszustwach inwestycyjnych",
        "piramidach finansowych", "testamencie i dziedziczeniu", "spadku z długami", "zwrocie podatku",
        "przekazaniu 1,5% podatku", "darowiznach na cele charytatywne",
    ],
    "technologii i internecie": [
        "smartfonach", "iPhonie", "Androidzie", "telefonach Samsunga i Xiaomi", "telefonach dla seniorów",
        "naprawie telefonu", "przenoszeniu danych na nowy telefon", "baterii i ładowarkach", "laptopach",
        "budowie komputera", "kartach graficznych", "dyskach SSD", "Windowsie 11", "macOS", "Linuksie",
        "aktualizacjach systemu", "przeglądarkach internetowych", "wyszukiwarce Google", "Gmailu i Outlooku",
        "Wordzie i Excelu", "PowerPoincie", "Google Docs", "Canvie", "edycji zdjęć", "montażu wideo",
        "aparatach i fotografii", "routerze i Wi-Fi", "światłowodzie", "sieci 5G", "inteligentnym domu",
        "inteligentnych żarówkach", "kamerach monitoringu", "robotach sprzątających", "drukarkach",
        "drukarce 3D", "smartwatchach", "słuchawkach bezprzewodowych", "telewizorach i soundbarach",
        "e-czytnikach", "dronach", "chmurze i kopiach zapasowych", "bezpieczeństwie haseł",
        "menedżerze haseł", "uwierzytelnianiu dwuskładnikowym", "antywirusie", "VPN-ie", "phishingu",
        "fałszywych SMS-ach", "telefonach od oszustów", "kradzieży tożsamości", "wycieku danych",
        "atakach ransomware", "deepfake'ach", "fake newsach", "prywatności w internecie", "RODO",
        "ochronie dzieci w sieci", "kontroli rodzicielskiej", "mediach społecznościowych", "Facebooku",
        "Instagramie", "TikToku", "YouTubie", "kanale na YouTubie", "X i Twitterze", "WhatsAppie i Messengerze",
        "Signalu i Telegramie", "Discordzie", "Twitchu", "streamingu", "Netfliksie", "Spotify", "podcastach",
        "e-bookach i audiobookach", "grach komputerowych", "konsolach PlayStation i Xbox", "Nintendo Switch",
        "Steamie", "„Wiedźminie 3”", "„Cyberpunku 2077”", "Minecrafcie", "sztucznej inteligencji",
        "ChatGPT i chatbotach", "generowaniu obrazów przez AI", "AI w szkole", "AI w pracy", "programowaniu",
        "nauce programowania", "Pythonie", "JavaScripcie", "tworzeniu stron internetowych", "WordPressie",
        "sklepie internetowym", "domenie i hostingu", "Raspberry Pi i Arduino", "bankowości mobilnej",
        "zakupach na Allegro", "elektrośmieciach", "samochodach elektrycznych",
    ],
    "podróżach po Polsce": [
        "Krakowie", "Warszawie", "Gdańsku", "Sopocie", "Gdyni", "Wrocławiu", "Poznaniu", "Łodzi",
        "Toruniu", "Lublinie", "Białymstoku", "Szczecinie", "Katowicach", "Bydgoszczy", "Rzeszowie",
        "Kielcach", "Olsztynie", "Opolu", "Zielonej Górze", "Gorzowie Wielkopolskim", "Radomiu", "Płocku",
        "Elblągu", "Tarnowie", "Nowym Sączu", "Przemyślu", "Sandomierzu", "Kaliszu", "Lesznie", "Gnieźnie",
        "Suwałkach", "Łomży", "Siedlcach", "Chełmie", "Zamościu", "Jeleniej Górze", "Wałbrzychu", "Legnicy",
        "Koszalinie", "Słupsku", "Gliwicach", "Bytomiu", "Sosnowcu", "Bielsku-Białej", "Cieszynie", "Pile",
        "Grudziądzu", "Inowrocławiu", "Ciechocinku", "Kołobrzegu", "Świnoujściu", "Łebie", "Ustce",
        "Mielnie", "Krynicy Morskiej", "Zakopanem", "Szczawnicy", "Krynicy-Zdroju", "Karpaczu",
        "Szklarskiej Porębie", "Wiśle w Beskidach", "Ustroniu", "Polanicy-Zdroju", "Kłodzku", "Nysie",
        "Paczkowie", "Kazimierzu Dolnym", "Nałęczowie", "Janowcu", "Kozłówce", "Łańcucie", "Krasiczynie",
        "Baranowie Sandomierskim", "Malborku", "Fromborku", "Reszlu", "Świętej Lipce", "Mikołajkach",
        "Giżycku", "Augustowie", "Sejnach", "Tykocinie", "Supraślu", "Kruszynianach", "Białowieży",
        "Hajnówce", "Sanoku", "Lesku", "Ustrzykach Dolnych", "Wetlinie", "Bieczu", "Lanckoronie",
        "Wadowicach", "Kalwarii Zebrzydowskiej", "Ojcowie", "Pszczynie", "Nikiszowcu", "Tarnowskich Górach",
        "Zabrzu i kopalni Guido", "Wieliczce", "Częstochowie", "Muzeum Auschwitz-Birkenau", "Książu",
        "Mosznej", "Niedzicy i Czorsztynie", "Ogrodzieńcu", "zamkach", "pałacach", "skansenach", "muzeach",
        "zabytkach UNESCO", "uzdrowiskach", "termach i aquaparkach", "Termach Chochołowskich",
        "parkach rozrywki", "Energylandii", "ogrodach zoologicznych", "Bałtowie i Parku Jurajskim",
        "kopalni złota w Złotym Stoku", "spływie Dunajcem", "Mazurach na kajaku", "rejsach statkiem",
        "Bieszczadach pod namiotem", "kempingach", "glampingu", "domkach letniskowych", "agroturystyce",
        "schroniskach górskich", "szlakach rowerowych", "Green Velo", "kamperach", "rezerwacji noclegów",
        "podróżach autem", "PKP Intercity i Pendolino", "pociągach regionalnych", "Flixbusie",
        "lotniskach regionalnych", "biletach i zniżkach", "wakacjach z dziećmi", "weekendzie we dwoje",
        "podróżach z psem", "Bałtyku poza sezonem", "zimowych wyjazdach", "kuchni regionalnej w podróży",
    ],
    "edukacji w Polsce": [
        "żłobku", "przedszkolu", "zerówce", "edukacji przedszkolnej", "świetlicy szkolnej", "obiadach w szkole",
        "wyborze szkoły średniej", "liceum", "technikum", "szkole branżowej", "szkołach prywatnych",
        "szkołach katolickich", "szkołach Montessori", "edukacji domowej", "egzaminie ósmoklasisty",
        "maturze z polskiego", "maturze z matematyki", "maturze z angielskiego", "maturze rozszerzonej",
        "maturze międzynarodowej IB", "kartkówkach i sprawdzianach", "ocenach", "pracy domowej",
        "korepetycjach", "nauce do egzaminu", "technikach zapamiętywania", "fiszkach", "nauce angielskiego",
        "nauce języków z aplikacjami", "nauce matematyki", "nauce historii", "olimpiadach przedmiotowych",
        "olimpiadzie matematycznej", "dysleksji", "ADHD u dzieci w szkole", "wychowawcy", "radzie rodziców",
        "wycieczkach szkolnych", "religii i etyce w szkole", "nauczaniu zdalnym", "podstawie programowej",
        "reformie edukacji", "Karcie Nauczyciela", "zarobkach nauczycieli", "wyborze kierunku studiów",
        "rekrutacji na studia", "studiach dziennych i zaocznych", "kierunku lekarskim", "stomatologii",
        "farmacji", "pielęgniarstwie", "ratownictwie medycznym", "fizjoterapii", "dietetyce", "psychologii",
        "weterynarii", "prawie", "administracji", "ekonomii", "finansach i rachunkowości", "zarządzaniu",
        "logistyce", "informatyce", "automatyce i robotyce", "mechatronice", "elektrotechnice",
        "budownictwie", "architekturze", "geodezji", "górnictwie", "lotnictwie", "biotechnologii", "chemii",
        "fizyce", "matematyce", "astronomii", "filologii polskiej", "anglistyce", "germanistyce", "japonistyce",
        "sinologii", "historii sztuki", "archeologii", "filozofii", "socjologii", "politologii",
        "stosunkach międzynarodowych", "dziennikarstwie", "kulturoznawstwie", "pedagogice", "logopedii",
        "kosmetologii", "turystyce i rekreacji", "AWF-ie", "Akademii Sztuk Pięknych", "Akademii Muzycznej",
        "szkole filmowej w Łodzi", "Akademii Teatralnej", "Uniwersytecie Jagiellońskim",
        "Uniwersytecie Warszawskim", "Politechnice Warszawskiej", "AGH", "SGH", "Politechnice Wrocławskiej",
        "Uniwersytecie im. Adama Mickiewicza", "uczelniach medycznych", "akademikach i stancjach",
        "juwenaliach", "sesji egzaminacyjnej", "poprawkach i warunkach", "urlopie dziekańskim",
        "zmianie kierunku studiów", "stypendiach", "kredycie studenckim", "Erasmusie", "studiach za granicą",
        "pisaniu pracy magisterskiej", "plagiacie", "doktoracie", "bibliotekach", "kursach online",
        "uniwersytecie trzeciego wieku",
    ],
    "rodzinie i wychowaniu dzieci": [
        "staraniu się o dziecko", "niepłodności", "in vitro", "ciąży i badaniach prenatalnych", "porodzie",
        "połogu", "depresji poporodowej", "urlopie tacierzyńskim", "wyprawce dla noworodka", "noworodku",
        "karmieniu piersią", "kolkach", "śnie niemowlęcia", "smoczku", "rozszerzaniu diety", "ząbkowaniu",
        "pierwszych krokach", "wózkach i fotelikach samochodowych", "nocnikowaniu", "żłobku i nianiach",
        "adaptacji w przedszkolu", "buncie dwulatka", "zabawach sensorycznych", "zabawkach", "czytaniu dzieciom",
        "bajkach i kreskówkach", "zasadach w domu", "karach i nagrodach", "wychowaniu bez klapsów",
        "rodzicielstwie bliskości", "metodzie Montessori w domu", "czasie przed ekranem",
        "pierwszym telefonie dziecka", "grach komputerowych dzieci", "cyberprzemocy", "kieszonkowym",
        "obowiązkach domowych", "rodzeństwie", "zazdrości o rodzeństwo", "kłótniach rodzeństwa",
        "dziecku z niepełnosprawnością", "dziecku z autyzmem", "dziecku z ADHD", "dojrzewaniu",
        "rozmowach o dojrzewaniu i seksualności", "nastolatkach", "nastolatkach a alkoholu",
        "przemocy rówieśniczej", "wyborze szkoły przez dziecko", "dorosłych dzieciach", "pustym gnieździe",
        "urodzinach dziecka", "imionach dla dzieci", "chrzcie", "rodzicach chrzestnych", "komunii",
        "osiemnastce dziecka", "zwierzęciu dla dziecka", "wakacjach z dziećmi", "świętach z rodziną",
        "rodzinnych kłótniach przy świętach", "rodzinnych tradycjach", "drzewie genealogicznym", "dziadkach",
        "opiece nad wnukami", "relacjach z teściami", "aplikacjach randkowych", "pierwszej randce",
        "zaręczynach", "ślubie i weselu", "ślubie kościelnym", "intercyzie", "wspólnym mieszkaniu",
        "podziale obowiązków w związku", "związkach na odległość", "planowaniu rodziny", "bezdzietności",
        "kryzysie w związku", "zdradzie", "terapii par", "rozstaniu", "rozwodzie i opiece nad dziećmi",
        "randkowaniu po rozwodzie", "samotnym rodzicielstwie", "rodzinie patchworkowej", "adopcji",
        "rodzinie zastępczej", "starzeniu się rodziców", "demencji rodzica", "domu opieki",
        "opiece nad chorym rodzicem", "podziale majątku w rodzinie",
    ],
    "domu, ogrodzie i majsterkowaniu": [
        "remoncie łazienki", "małej łazience", "kuchni na wymiar", "meblach na wymiar", "garderobie",
        "pokoju dziecięcym", "aranżacji wnętrz", "małym mieszkaniu", "przechowywaniu", "malowaniu ścian",
        "tapetach", "gładziach i tynkach", "kafelkach", "fugach i silikonie", "pleśni na fugach",
        "panelach podłogowych", "wierceniu w ścianie", "wieszaniu półek i karniszy", "renowacji starych mebli",
        "malowaniu mebli", "hydraulice", "cieknącym kranie", "zatkanym odpływie", "bojlerze", "elektryce",
        "gniazdkach i bezpiecznikach", "oświetleniu LED", "narzędziach", "elektronarzędziach",
        "wkrętarce i szlifierce", "warsztacie w domu", "ociepleniu domu", "dociepleniu poddasza",
        "oknach i ich wymianie", "drzwiach antywłamaniowych", "alarmie domowym", "dachu i rynnach",
        "elewacji", "pompie ciepła", "fotowoltaice", "piecu gazowym", "piecu na pellet", "kominku",
        "drewnie do kominka", "ogrzewaniu podłogowym", "termostatach", "klimatyzacji", "rekuperacji",
        "oczyszczaczu powietrza", "wilgoci i grzybie", "zapachach w mieszkaniu", "molach ubraniowych",
        "insektach w domu", "sprzątaniu", "sprzątaniu po remoncie", "praniu", "plamach", "środkach czystości",
        "zmywarce", "pralce i suszarce", "lodówce", "odkurzaczu bezprzewodowym", "meblach", "balkonie",
        "tarasie", "ogrodzie zimowym", "zakupie działki", "budowie domu", "projektach domów", "garażu",
        "ogrodzeniu", "kostce brukowej i podjeździe", "studni", "szambie i przydomowej oczyszczalni",
        "deszczówce", "nawadnianiu", "trawniku", "trawie z rolki", "mchu na trawniku", "kosiarce",
        "kretach i nornicach", "warzywniku", "warzywniku podwyższonym", "pomidorach", "uprawie ogórków",
        "uprawie truskawek", "ziołach na parapecie", "drzewach owocowych", "przycinaniu drzew",
        "szczepieniu drzew", "różach i hortensjach", "lawendzie", "kompostowniku", "nawozach",
        "szkodnikach w ogrodzie", "mszycach", "ślimakach", "roślinach doniczkowych", "storczykach",
        "zimowaniu roślin", "grillu", "altanie", "oczku wodnym", "basenie ogrodowym", "huśtawce dla dzieci",
        "domku na drzewie",
    ],
    "motoryzacji": [
        "kupnie używanego samochodu", "sprowadzaniu auta z Niemiec", "sprzedaży auta",
        "umowie kupna-sprzedaży samochodu", "przeglądzie technicznym", "wymianie opon",
        "oponach zimowych i całorocznych", "wymianie oleju", "rozrządzie", "akumulatorze",
        "klimatyzacji w aucie", "LPG", "dieslu i benzynie", "hybrydach", "samochodach elektrycznych",
        "ładowarkach na trasie", "spalaniu paliwa", "jeździe ekonomicznej", "Toyocie", "Skodzie",
        "Volkswagenie", "Dacii", "Fiacie 126p", "Polonezie", "Syrenie", "zabytkowych samochodach",
        "żółtych tablicach", "mechaniku i warsztacie", "diagnostyce komputerowej", "lakierowaniu",
        "detailingu", "tuningu", "szkodzie i odszkodowaniu", "kolizji", "wypadku drogowym",
        "ubezpieczeniu OC i AC", "mandatach", "punktach karnych", "fotoradarach",
        "odcinkowym pomiarze prędkości", "autostradach i opłatach", "e-TOLL", "jeździe zimą",
        "jeździe po alkoholu", "egzaminie na prawo jazdy", "WORD-zie", "kursie prawa jazdy",
        "parkowaniu równoległym", "jeździe z dziećmi", "motocyklach", "skuterach", "rowerach elektrycznych",
        "przyczepach i holowaniu", "kamperach", "Strefach Czystego Transportu", "leasingu auta",
        "wynajmie samochodu", "Formule 1", "rajdach samochodowych",
    ],
    "zwierzętach domowych": [
        "psach", "kotach", "adopcji psa ze schroniska", "szczeniakach", "kociętach", "rasach psów",
        "owczarku niemieckim", "labradorze", "jamniku", "buldogu francuskim", "kundelkach",
        "kotach brytyjskich", "maine coonach", "karmie dla psa", "karmie dla kota", "diecie BARF",
        "weterynarzu", "szczepieniach psa", "kastracji i sterylizacji", "pchłach i kleszczach u psa",
        "odrobaczaniu", "chipowaniu zwierząt", "paszporcie dla psa", "podróżach z psem", "szkoleniu psa",
        "behawioryście", "lęku separacyjnym", "szczekaniu", "gryzieniu mebli", "kuwecie", "drapakach",
        "kotach wychodzących", "starym psie", "eutanazji zwierzęcia", "żałobie po zwierzęciu", "chomikach",
        "świnkach morskich", "królikach", "papugach", "rybkach akwariowych", "akwarium", "żółwiach",
        "gadach w terrarium", "koniach", "kurach w ogrodzie", "przydomowej pasiece",
        "ubezpieczeniu zwierzęcia", "hotelach dla zwierząt", "petsitterach", "zwierzętach w bloku",
        "alergii na sierść", "dzieciach i psach", "sprzątaniu po psie", "obroży i szelkach",
        "zabawkach dla psa", "wybiegach dla psów",
    ],
    "nauce i technice": [
        "Mikołaju Koperniku", "Janie Heweliuszu", "Marii Skłodowskiej-Curie", "Ignacym Łukasiewiczu",
        "Kazimierzu Funku", "Stefanie Banachu", "szkole lwowsko-warszawskiej", "Ludwiku Hirszfeldzie",
        "Rudolfie Weiglu", "Janie Czochralskim", "Mirosławie Hermaszewskim", "polskich astronautach",
        "nagrodach Nobla dla Polaków", "Centrum Nauki Kopernik", "Polskiej Akademii Nauk",
        "kosmosie i astronomii", "zaćmieniach", "zorzach polarnych w Polsce", "meteorach", "teleskopach",
        "czarnych dziurach", "ewolucji", "genetyce", "testach genetycznych", "szczepionkach mRNA",
        "antybiotykooporności", "fizyce kwantowej", "teorii względności", "energii jądrowej",
        "fuzji jądrowej", "elektryczności i magnetyzmie", "chemii w kuchni", "doświadczeniach dla dzieci",
        "matematyce na co dzień", "zagadkach logicznych", "liczbach pierwszych", "prawdopodobieństwie",
        "statystyce", "robotyce", "komputerach kwantowych", "wynalazkach", "patentach", "polskich startupach",
        "dinozaurach", "paleontologii", "wulkanach", "meteorologii", "oceanach", "mózgu",
        "śnie z perspektywy nauki", "psychologii eksperymentalnej", "metodzie naukowej",
        "fake newsach naukowych", "popularyzacji nauki",
    ],
}
