"""Tematy i podtematy promptu systemowego.

Klucz = temat w miejscowniku (po „Rozmowa o …”), wartość = podtematy w miejscowniku (po „o …”).
Do każdego zapytania losujemy podzbiór podtematów w losowej kolejności (zob. prompt.build_jobs),
żeby uniknąć mode collapse. Zmiana tej listy zmienia zadania wynikające z --master-seed, więc
wznawiany run musi używać tej samej wersji pliku.
"""

SUBTOPICS: dict[str, list[str]] = {
    "historii Polski": [
        "Słowianach i plemionach przed Mieszkiem", "Mieszku I i chrzcie Polski", "Bolesławie Chrobrym",
        "rozbiciu dzielnicowym", "Kazimierzu Wielkim", "Jadwidze Andegaweńskiej", "Władysławie Jagielle",
        "unii polsko-litewskiej", "bitwie pod Grunwaldem", "Zygmuncie Starym i Zygmuncie Auguście",
        "unii lubelskiej", "Rzeczypospolitej Obojga Narodów", "wolnej elekcji", "Stefanie Batorym",
        "potopie szwedzkim", "Janie III Sobieskim", "odsieczy wiedeńskiej", "konfederacji barskiej",
        "Stanisławie Auguście Poniatowskim", "Konstytucji 3 maja", "rozbiorach",
        "insurekcji kościuszkowskiej", "Legionach Dąbrowskiego", "Księstwie Warszawskim",
        "powstaniu listopadowym", "Wielkiej Emigracji", "rabacji galicyjskiej", "powstaniu styczniowym",
        "pracy organicznej", "odzyskaniu niepodległości w 1918 roku", "Józefie Piłsudskim",
        "Romanie Dmowskim", "wojnie polsko-bolszewickiej", "II Rzeczypospolitej", "przewrocie majowym",
        "kampanii wrześniowej", "Westerplatte", "Katyniu", "Polskim Państwie Podziemnym",
        "powstaniu warszawskim", "okupacji niemieckiej i sowieckiej",
        "Zagładzie Żydów na ziemiach polskich", "żołnierzach wyklętych", "PRL-u", "Gomułce i Gierku",
        "Czerwcu 1956 i Marcu 1968", "wydarzeniach grudniowych 1970", "kartkach na żywność",
        "papieżu Janie Pawle II", "Sierpniu 1980 i Solidarności", "Lechu Wałęsie", "stanie wojennym",
        "Okrągłym Stole", "transformacji ustrojowej", "wejściu Polski do NATO i Unii Europejskiej",
        "historii swojego regionu", "Kresach Wschodnich",
    ],
    "polskiej kulturze i literaturze": [
        "Janie Kochanowskim", "Adamie Mickiewiczu", "Juliuszu Słowackim", "Henryku Sienkiewiczu",
        "Bolesławie Prusie", "Elizie Orzeszkowej", "Marii Konopnickiej", "Stefanie Żeromskim",
        "Władysławie Reymoncie", "Stanisławie Wyspiańskim", "Bolesławie Leśmianie", "Julianie Tuwimie",
        "Brunonie Schulzu", "Witoldzie Gombrowiczu", "Czesławie Miłoszu", "Zbigniewie Herbercie",
        "Tadeuszu Różewiczu", "Wisławie Szymborskiej", "Stanisławie Lemie", "Ryszardzie Kapuścińskim",
        "Oldze Tokarczuk", "Andrzeju Sapkowskim", "lekturach szkolnych", "romantyzmie", "Młodej Polsce",
        "poezji współczesnej", "reportażu", "fantastyce", "kryminałach", "literaturze dziecięcej",
        "polskim kinie", "filmach Wajdy i Kieślowskiego", "Pawle Pawlikowskim",
        "polskich komediach filmowych", "Teatrze Telewizji", "teatrze i kabarecie", "Fryderyku Chopinie",
        "Stanisławie Moniuszce", "operze i filharmonii", "polskim jazzie", "Krzysztofie Komedzie",
        "muzyce ludowej", "kolędach", "polskim rocku i hip-hopie", "disco polo",
        "malarstwie Matejki i Malczewskiego", "polskim plakacie", "architekturze zabytkowej",
        "sztuce ludowej i wycinankach", "polskich legendach i baśniach",
        "obrzędach i zwyczajach świątecznych", "polskich grach wideo", "muzeach i festiwalach",
        "polskich serialach", "polskich podcastach i youtuberach",
    ],
    "polskiej kuchni": [
        "pierogach", "bigosie", "żurku i zakwasie", "barszczu czerwonym", "rosole", "zupie ogórkowej",
        "kapuśniaku", "flakach", "chłodniku", "zupie grzybowej", "kotlecie schabowym", "gołąbkach",
        "golonce", "kaszance", "plackach ziemniaczanych", "kopytkach", "kluskach śląskich", "pyzach",
        "racuchach", "kiszonkach", "kiszeniu ogórków", "grzybach i grzybobraniu", "wędlinach i kiełbasach",
        "oscypku i serach regionalnych", "chlebie na zakwasie", "śledziach", "karpiu",
        "dwunastu potrawach wigilijnych", "wielkanocnym stole", "pączkach i tłustym czwartku",
        "faworkach", "szarlotce", "sernikach i makowcach", "pierniku toruńskim", "kompocie",
        "kuchni śląskiej", "kuchni podhalańskiej", "kuchni kaszubskiej", "kuchni kresowej",
        "przetworach i dżemach", "nalewkach", "kaszach", "potrawach z ziemniaków", "przyprawach",
        "wegetariańskich wersjach polskich dań", "kuchni wegańskiej", "niedzielnym obiedzie",
        "obiadach dla dzieci", "przepisach babci", "gotowaniu przy małym budżecie", "barach mlecznych",
    ],
    "sprawach urzędowych w Polsce": [
        "dowodzie osobistym", "paszporcie", "paszporcie dla dziecka", "meldunku", "numerze PESEL",
        "zmianie nazwiska", "ślubie cywilnym", "rejestracji urodzenia dziecka", "aktach stanu cywilnego",
        "zeznaniu PIT", "zwrocie podatku", "uldze na dzieci", "podatku od spadków i darowizn",
        "jednoosobowej działalności gospodarczej", "CEIDG", "VAT", "kasie fiskalnej", "KRS i spółkach",
        "składkach ZUS", "emeryturze", "zwolnieniu lekarskim", "zasiłku opiekuńczym",
        "urlopie macierzyńskim i rodzicielskim", "świadczeniu 800 plus", "becikowym",
        "karcie dużej rodziny", "dodatku mieszkaniowym", "orzeczeniu o niepełnosprawności",
        "NFZ i skierowaniach", "e-recepcie", "Internetowym Koncie Pacjenta", "rejestracji samochodu",
        "dowodzie rejestracyjnym", "prawie jazdy", "mandatach", "abonamencie RTV", "opłacie śmieciowej",
        "rozwodzie", "spadku i notariuszu", "księgach wieczystych", "sprzedaży mieszkania",
        "pozwoleniu na budowę", "podatku od nieruchomości", "profilu zaufanym i mObywatelu", "ePUAP",
        "wyborach", "urzędzie pracy i zasiłku", "zaświadczeniu o niekaralności", "zgłoszeniu kradzieży",
        "reklamacji i prawach konsumenta", "sprawach w sądzie", "odwołaniu od decyzji",
        "dostępie do informacji publicznej",
    ],
    "języku polskim": [
        "pisowni ó i u", "pisowni rz i ż", "pisowni ch i h", "pisowni „nie” z różnymi częściami mowy",
        "pisowni łącznej i rozdzielnej", "przecinkach", "wielkiej i małej literze",
        "pisowni nazw geograficznych", "odmianie nazwisk", "odmianie liczebników",
        "liczbie mnogiej rzeczowników", "rodzajach gramatycznych", "przypadkach", "wołaczu",
        "aspekcie czasowników", "trybie przypuszczającym", "imiesłowach", "stronie biernej",
        "szyku zdania", "zaimku „swój”", "formach „poszłem” i „poszedłem”", "akcentowaniu wyrazów",
        "formach grzecznościowych", "zwrotach grzecznościowych w listach", "związkach frazeologicznych",
        "przysłowiach", "pochodzeniu słów", "słowotwórstwie", "zdrobnieniach", "neologizmach",
        "zapożyczeniach z angielskiego", "slangu młodzieżowym", "języku internetu", "wulgaryzmach",
        "eufemizmach", "gwarach i regionalizmach", "dialektach góralskich", "języku śląskim i kaszubskim",
        "wymowie", "częstych błędach językowych", "feminatywach", "skrótowcach",
        "transkrypcji obcych nazwisk", "pisaniu oficjalnych maili", "pisaniu CV i listu motywacyjnego",
        "korekcie tekstu", "synonimach", "różnicach znaczeniowych podobnych słów", "zapisie dialogów",
        "rymach i wierszach", "nazwach miejscowości i ich odmianie", "nauce czytania u dzieci",
    ],
    "polskiej geografii i przyrodzie": [
        "Tatrach", "Pieninach", "Beskidach", "Bieszczadach", "Sudetach", "Karkonoszach", "Roztoczu",
        "Jurze Krakowsko-Częstochowskiej", "Szlaku Orlich Gniazd", "Mazurach", "Śniardwach", "Kaszubach",
        "Podlasiu", "Wielkopolsce", "Śląsku", "Żuławach", "Bałtyku i plażach", "Helu i Mierzei Wiślanej",
        "Słowińskim Parku Narodowym", "wydmach", "Wiśle", "Odrze", "Bugu i Narwi", "jeziorach",
        "torfowiskach", "Puszczy Białowieskiej", "żubrach", "bocianach", "bobrach", "fokach bałtyckich",
        "wilkach i rysiach", "niedźwiedziach", "dzikach w miastach", "żmijach", "kleszczach", "pszczołach",
        "ptakach i ich przylotach", "grzybach leśnych", "gatunkach inwazyjnych", "parkach narodowych",
        "rezerwatach przyrody", "ochronie przyrody", "jaskiniach", "Pustyni Błędowskiej",
        "klimacie i pogodzie", "porach roku", "burzach i nawałnicach", "suszy i powodziach", "smogu",
        "segregacji śmieci", "lasach i wycince drzew", "kopalniach i węglu", "energii odnawialnej",
        "rolnictwie", "województwach", "dużych miastach", "małych miasteczkach i wsiach",
        "ogrodach i działkach",
    ],
    "codziennym życiu w Polsce": [
        "wynajmie mieszkania", "kredycie hipotecznym", "rachunkach za prąd i gaz", "abonamencie telefonicznym",
        "internecie domowym", "zakupach w dyskontach", "zakupach na targu", "zakupach w internecie",
        "paczkomatach", "dostawach jedzenia", "cenach i inflacji", "komunikacji miejskiej",
        "rowerach miejskich", "hulajnogach elektrycznych", "parkowaniu w mieście", "korkach",
        "podróżach pociągiem", "dojazdach samochodem", "dojazdach do pracy", "pracy biurowej",
        "pracy zdalnej", "umowie o pracę i umowie zleceniu", "szukaniu pracy", "lekarzu rodzinnym",
        "kolejkach do specjalistów", "dentyście", "aptece", "fryzjerze", "przedszkolu i szkole",
        "maturze", "studiach", "opiece nad dziećmi", "opiece nad starszymi rodzicami",
        "zwierzętach domowych", "remontach", "sprzątaniu", "sąsiadach i wspólnocie mieszkaniowej",
        "hałasie", "weekendach i wolnym czasie", "kinie i teatrze", "urlopie nad morzem i w górach",
        "majówce", "feriach zimowych", "świętach rodzinnych", "imieninach", "prezentach", "Dniu Matki",
        "andrzejkach", "sylwestrze", "ślubach i weselach", "Wszystkich Świętych", "bankowości i BLIK-u",
        "oszczędzaniu",
    ],
    "sporcie w Polsce": [
        "reprezentacji Polski w piłce nożnej", "Ekstraklasie", "Lechu Poznań i Legii Warszawa", "derbach",
        "Lidze Mistrzów", "mundialu", "mistrzostwach Europy", "Robercie Lewandowskim", "siatkówce",
        "Bartoszu Kurku", "tenisie i Idze Świątek", "Hubercie Hurkaczu", "tenisie stołowym", "badmintonie",
        "skokach narciarskich", "Adamie Małyszu", "Kamilu Stochu", "Justynie Kowalczyk",
        "narciarstwie zjazdowym", "snowboardzie", "łyżwiarstwie", "hokeju", "żużlu", "piłce ręcznej",
        "koszykówce", "lekkoatletyce", "Anicie Włodarczyk", "pływaniu", "Otylii Jędrzejczak",
        "igrzyskach olimpijskich", "sporcie niepełnosprawnych", "kolarstwie i Tour de Pologne",
        "maratonach", "triathlonie", "bieganiu dla początkujących", "nordic walking",
        "jeździe na rowerze", "siłowni i fitnessie", "crossficie", "jodze", "żeglarstwie", "kajakach",
        "wioślarstwie", "wspinaczce", "szachach", "sportach walki i boksie", "MMA i galach KSW", "golfie",
        "rajdach samochodowych", "e-sporcie", "kibicowaniu i stadionach", "wychowaniu fizycznym w szkole",
        "kontuzjach sportowych", "diecie sportowca",
    ],
    "zdrowiu": [
        "przeziębieniu i grypie", "szczepieniach", "alergiach", "migrenie", "bólu pleców", "cukrzycy",
        "nadciśnieniu", "chorobach serca", "zdrowej diecie", "odchudzaniu", "witaminach i suplementach",
        "śnie i bezsenności", "stresie", "wypaleniu", "depresji", "wizycie u psychologa",
        "zdrowiu psychicznym nastolatków", "badaniach okresowych", "morfologii krwi",
        "badaniach profilaktycznych", "pierwszej pomocy", "lekach bez recepty", "zdrowiu dzieci", "ciąży",
        "menopauzie", "zdrowiu seniorów", "zębach", "wzroku i okularach", "słuchu", "skórze i trądziku",
        "opalaniu i kremach z filtrem", "kleszczach i boreliozie", "rzucaniu palenia", "alkoholu",
        "aktywności fizycznej", "rehabilitacji", "fizjoterapii", "prywatnych abonamentach medycznych",
        "szpitalnym oddziale ratunkowym", "ergonomii pracy przy komputerze",
    ],
    "pracy i karierze": [
        "pisaniu CV", "rozmowie kwalifikacyjnej", "pierwszej pracy", "stażu", "pracy dla studentów",
        "negocjacjach wynagrodzenia", "podwyżce", "awansie", "zmianie branży", "przekwalifikowaniu",
        "kursach i certyfikatach", "pracy zdalnej", "pracy hybrydowej", "pracy zmianowej", "umowie B2B",
        "umowie o dzieło", "okresie wypowiedzenia", "zwolnieniu z pracy", "świadectwie pracy",
        "urlopie wypoczynkowym", "nadgodzinach", "płacy minimalnej", "PPK", "benefitach pracowniczych",
        "BHP", "mobbingu", "relacjach z szefem", "pracy w zespole", "pracy w korporacji",
        "pracy w budżetówce", "pracy w handlu", "pracy w IT", "pracy nauczyciela",
        "pracy w służbie zdrowia", "własnej firmie", "freelancingu", "LinkedInie", "wypaleniu zawodowym",
        "równowadze między pracą a życiem", "powrocie z emigracji",
    ],
    "finansach osobistych": [
        "budżecie domowym", "funduszu awaryjnym", "oszczędzaniu na emeryturę", "IKE i IKZE",
        "obligacjach skarbowych", "lokatach", "kontach oszczędnościowych", "inwestowaniu w ETF-y",
        "giełdzie", "kryptowalutach", "podatku Belki", "kredycie gotówkowym", "karcie kredytowej",
        "debecie", "zakupach na raty", "leasingu", "BIK-u", "zadłużeniu", "komornikach", "spłacie kredytu",
        "kupnie pierwszego mieszkania", "programach rządowych na mieszkanie", "wynajmie jako inwestycji",
        "inflacji", "kursie złotego", "ubezpieczeniu na życie", "OC i AC", "ubezpieczeniu mieszkania",
        "kieszonkowym dla dzieci", "rachunku dla dziecka", "finansach w związku", "rachunkach i opłatach",
        "oszczędzaniu na zakupach spożywczych", "zakupach z drugiej ręki", "oszustwach na BLIK-a",
        "phishingu bankowym", "testamencie i dziedziczeniu", "zwrocie podatku",
    ],
    "technologii i internecie": [
        "smartfonach", "laptopach", "telefonach dla seniorów", "naprawie telefonu",
        "ładowarkach i bateriach", "routerze i Wi-Fi", "światłowodzie", "sieci 5G", "inteligentnym domu",
        "drukarkach", "chmurze i kopiach zapasowych", "bezpieczeństwie haseł",
        "uwierzytelnianiu dwuskładnikowym", "phishingu", "prywatności w internecie", "RODO",
        "ochronie dzieci w sieci", "kontroli rodzicielskiej", "fake newsach", "mediach społecznościowych",
        "TikToku", "YouTubie", "streamingu", "podcastach", "e-bookach", "grach komputerowych",
        "sztucznej inteligencji", "chatbotach", "programowaniu", "nauce programowania", "Excelu",
        "bankowości mobilnej", "zakupach na Allegro", "aparatach i fotografii", "edycji zdjęć",
        "elektrośmieciach", "samochodach elektrycznych",
    ],
    "podróżach po Polsce": [
        "Krakowie", "Warszawie", "Gdańsku", "Sopocie", "Wrocławiu", "Poznaniu", "Toruniu", "Lublinie",
        "Białymstoku", "Szczecinie", "Zakopanem", "Kazimierzu Dolnym", "Zamościu", "Malborku",
        "Wieliczce", "Częstochowie", "Muzeum Auschwitz-Birkenau", "zamkach", "pałacach", "skansenach",
        "muzeach", "zabytkach UNESCO", "uzdrowiskach", "parkach rozrywki", "Mazurach na kajaku",
        "Bieszczadach pod namiotem", "agroturystyce", "schroniskach górskich", "szlakach rowerowych",
        "Green Velo", "kamperach", "noclegach", "podróżach autem", "PKP Intercity", "biletach i zniżkach",
        "wakacjach z dziećmi", "weekendzie we dwoje", "podróżach z psem", "Bałtyku poza sezonem",
        "zimowych wyjazdach", "kuchni regionalnej w podróży",
    ],
    "edukacji w Polsce": [
        "żłobku", "przedszkolu", "zerówce", "wyborze szkoły średniej", "liceum", "technikum",
        "szkole branżowej", "egzaminie ósmoklasisty", "maturze z matematyki", "kartkówkach i sprawdzianach",
        "ocenach", "pracy domowej", "korepetycjach", "nauce angielskiego", "nauce matematyki",
        "nauce historii", "olimpiadach przedmiotowych", "dysleksji", "ADHD u dzieci w szkole",
        "wychowawcy", "radzie rodziców", "wycieczkach szkolnych", "religii i etyce w szkole",
        "nauczaniu zdalnym", "edukacji domowej", "wyborze kierunku studiów", "rekrutacji na studia",
        "studiach dziennych i zaocznych", "stypendiach", "kredycie studenckim", "Erasmusie",
        "pisaniu pracy magisterskiej", "plagiacie", "doktoracie", "bibliotekach", "kursach online",
        "uniwersytecie trzeciego wieku",
    ],
    "rodzinie i wychowaniu dzieci": [
        "noworodku", "karmieniu piersią", "śnie niemowlęcia", "rozszerzaniu diety", "ząbkowaniu",
        "pierwszych krokach", "żłobku i nianiach", "buncie dwulatka", "zabawkach", "czytaniu dzieciom",
        "zasadach w domu", "karach i nagrodach", "czasie przed ekranem", "dzieciach a smartfonach",
        "kieszonkowym", "obowiązkach domowych", "rodzeństwie", "dojrzewaniu", "nastolatkach",
        "przemocy rówieśniczej", "urodzinach dziecka", "chrzcie", "komunii", "wakacjach z dziećmi",
        "świętach z rodziną", "dziadkach", "relacjach z teściami", "ślubie i weselu", "planowaniu rodziny",
        "kryzysie w związku", "rozstaniu", "rozwodzie i opiece nad dziećmi", "samotnym rodzicielstwie",
        "rodzinie patchworkowej", "adopcji", "rodzinie zastępczej", "opiece nad chorym rodzicem",
    ],
    "domu, ogrodzie i majsterkowaniu": [
        "remoncie łazienki", "malowaniu ścian", "kafelkach", "panelach podłogowych", "wierceniu w ścianie",
        "hydraulice", "elektryce", "narzędziach", "ociepleniu domu", "pompie ciepła", "fotowoltaice",
        "piecu gazowym", "kominku", "wilgoci i grzybie", "meblach", "aranżacji wnętrz", "małym mieszkaniu",
        "przechowywaniu", "sprzątaniu", "praniu", "plamach", "środkach czystości", "zakupie działki",
        "budowie domu", "projektach domów", "trawniku", "kosiarce", "warzywniku", "pomidorach",
        "drzewach owocowych", "kompostowniku", "nawadnianiu", "szkodnikach w ogrodzie", "ślimakach",
        "roślinach doniczkowych", "storczykach", "zimowaniu roślin", "grillu", "altanie", "oczku wodnym",
    ],
}
